### PR TITLE
Add support of function as arguments for utilities

### PR DESCRIPTION
**Pull request by lexich**

### CODE REVIEW

**Comment by ismamz** [comment]
Perfect! Thank you.
Regarding variables I thought that this plugin would come after compile (CSSNext, Sass or whatever). But, support of functions is absolutely necessary.

New utilities are welcome if you have one to add! :wink:

**Comment by lexich** [comment]
@ismamz Can you publish new version in npm repository?

**Comment by ismamz** [comment]
@lexich Done!

**Comment by lexich** [comment]
@ismamz Super! thx

**Comment by ismamz** [comment]
A small fix: [Support of string arguments added](https://github.com/ismamz/postcss-utilities/commit/6119e9025c6c95aba0f6f95444bcfaba3f6434a4)
Just for documenting it.

**Pull request merged**
